$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
inputs:
  train_data: 
    type: uri_folder
    path: ../../../data/
  n_estimators: 50
  max_depth: 10
outputs:
  model_output:
code: ../../../data-science/src/train_sa
command: >-
  python train.py 
  --train_data ${{inputs.train_data}}
  --model_output ${{outputs.model_output}}
  --regressor__n_estimators ${{inputs.n_estimators}}
  --regressor__max_depth ${{inputs.max_depth}}
environment: azureml:taxi-train-env@latest
compute: azureml:cpu-cluster
display_name: taxi-training-standalone
experiment_name: taxi-training-standalone
description: Train a scikit-learn regression model on the Taxi dataset.