name: train-and-deploy-model
on:
  workflow_dispatch:
    inputs:
      experiment_name:
        required: true
        type: string
        description: experiment name in AML workspace
        default: taxi-training-pipeline

  pull_request:
    branches:
      - main
    paths:
      - ml-pipelines/**
      - .github/workflows/deploy-model-training.yml
      - components/**
      - ci-cd/ghactions/**
jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: install-extension
      run:  |
        az extension add -n ml -y
        az configure --defaults group=${{vars.resource_group}} workspace=${{workspace_name}}

    - name: run job
      run: bash -x ./run-job.sh train/pipeline-code.yml ${{inputs.experiment_name}}
      working-directory: ml-pipelines/cli
