# Simple deployment pipeline REPLACE EXPERIMENT NAME
name: deploy-training-pipeline
on:
  workflow_dispatch:
    inputs:
      experiment_name:
        required: true
        type: string
        description: experiment name in AML workspace
        default: taxi-training-pipeline
  
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ steps.run-ml-pipeline.outputs.aml-job }}
    outputs:
       aml-job: ${{ steps.run-ml-pipeline.outputs.aml-job }}  
  
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      - name: install-extension
        run:  az extension add -n ml -y
     
      - name: run-ml-pipeline
        run: |
          run_id=$(az ml job create --file ml-pipelines/cli/train/pipeline.yml --resource-group ${{vars.resource_group}} \
          --workspace-name ${{vars.workspace_name}} --set experiment_name= ${{inputs.experiment_name}} --query name -o tsv)
          echo "JOB submitted $run_id"
          echo "aml-job=$(echo $run_id)" >> $GITHUB_OUTPUT;
        